ARG DOCKER_VERSION
ARG TARGETBIN
# Specific Container Registries
FROM plugins/${TARGETBIN}:latest as drone-xcr-plugin
FROM ghcr.io/dhpollack/drone-docker-buildx:${DOCKER_VERSION} as xcr
ARG TARGETBIN

COPY --from=drone-xcr-plugin /bin/drone-${TARGETBIN} /bin
RUN ln -s /bin/drone-docker-buildx /bin/drone-docker

ENV TARGETBIN=${TARGETBIN}

ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh", "/bin/drone-${TARGETBIN}"]
