name: Check Docker - Check docker dind version and create tag

on:
  schedule:
    - cron: '0 4 * * *'

defaults:
  run:
    shell: bash

jobs:
  check-dind:
    runs-on: ubuntu-latest
    outputs:
      dind_version: ${{ steps.dind.outputs.dind_version }}
    container:
      image: docker:dind
    steps:
      - name: 'Get latest dind version'
        id: dind
        shell: sh
        run: |
          echo "dind_version=$(echo $DOCKER_VERSION)" >> $GITHUB_OUTPUT

  compare-dind:
    needs: check-dind
    runs-on: ubuntu-latest
    outputs:
      comparison-result: ${{ steps.version.outputs.comparison-result }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 24.0.5
      - id: version
        uses: madhead/semver-utils@latest
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          compare-to: ${{ needs.check-dind.outputs.dind_version }}
  create-tag:
    needs: [check-dind, compare-dind]
    if: needs.compare-dind.outputs.comparison-result == '<'
    runs-on: ubuntu-latest
    steps:
      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: v${{ needs.check-dind.outputs.dind_version }}
      - name: Create tag
        if: steps.check-tag.outputs.exists == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DRONE_DOCKER_BUILDX_ADD_TAGS }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v' + '${{ needs.check-dind.outputs.dind_version }}',
              sha: context.sha
            })
