name: Tag - Build and Push Drone Docker Buildx Plugin

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 24.0.5
      - name: 'Get latest dind version'
        id: dind
        image: docker:dind
        shell: sh
        run: |
          echo "dind_version=$(echo $DOCKER_VERSION)" >> $GITHUB_OUTPUT
      - id: version
        uses: madhead/semver-utils@latest
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          compare-to: ${{ steps.dind.outputs.dind_version }}
      - run: |
          echo "${{ steps.version.outputs.release }}"           # 1.2.3
          echo "${{ steps.version.outputs.major }}"             # 1
          echo "${{ steps.version.outputs.minor }}"             # 2
          echo "${{ steps.version.outputs.patch }}"             # 3
          echo "${{ steps.version.outputs.build }}"             # 42.24
          echo "${{ steps.version.outputs.build-parts }}"       # 2
          echo "${{ steps.version.outputs.build-0 }}"           # 42
          echo "${{ steps.version.outputs.build-1 }}"           # 24
          echo "${{ steps.version.outputs.comparison-result }}" # <
          echo "${{ steps.version.outputs.satisfies }}"         # true
          echo "${{ steps.version.outputs.inc-major }}"         # 2.0.0
          echo "${{ steps.version.outputs.inc-premajor }}"      # 2.0.0-0
          echo "${{ steps.version.outputs.inc-minor }}"         # 1.3.0
          echo "${{ steps.version.outputs.inc-preminor }}"      # 1.3.0-0
          echo "${{ steps.version.outputs.inc-patch }}"         # 1.2.4
          echo "${{ steps.version.outputs.inc-prepatch }}"      # 1.2.4-0
          echo "${{ steps.version.outputs.inc-prerelease }}"    # 1.2.4-0
