name: Tag - Build and Push Drone Docker Buildx Plugin

on: [create]

defaults:
  run:
    shell: bash

jobs:
  build-base:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - id: version
        uses: madhead/semver-utils@latest
        with:
          version: ${{ github.ref_name }}
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          target: base
          file: Dockerfile.multiarch
          tags: |
            ghcr.io/dhpollack/drone-docker-buildx:${{ steps.version.outputs.release }}
            ghcr.io/dhpollack/drone-docker-buildx:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
            ghcr.io/dhpollack/drone-docker-buildx:${{ steps.version.outputs.major }}
            ghcr.io/dhpollack/drone-docker-buildx:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            DOCKER_VERSION=${{ steps.version.outputs.release }}
            BUILDX_VERSION=v0.11.2
            GITHUB_REF_NAME=${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-plugins:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    strategy:
      matrix:
        targetbin: [acr, gcr, ecr, heroku]
    runs-on: ubuntu-latest
    needs: build-base
    steps:
      - id: version
        uses: madhead/semver-utils@latest
        with:
          version: ${{ github.ref_name }}
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          target: xcr
          file: Dockerfile-registries.multiarch
          tags: |
            ghcr.io/dhpollack/drone-docker-buildx-${{ matrix.targetbin }}:${{ steps.version.outputs.release }}
            ghcr.io/dhpollack/drone-docker-buildx-${{ matrix.targetbin }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
            ghcr.io/dhpollack/drone-docker-buildx-${{ matrix.targetbin }}:${{ steps.version.outputs.major }}
            ghcr.io/dhpollack/drone-docker-buildx-${{ matrix.targetbin }}:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            TARGETBIN=${{ matrix.targetbin }}
            DOCKER_VERSION=${{ steps.version.outputs.release }}
