name: Tag - Build and Push Drone Docker Buildx Plugin

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - id: no_v
        run: |
          echo "ref_name_no_v=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
      - id: version
        uses: madhead/semver-utils@latest
        with:
          version: ${{ steps.no_v.outputs.ref_name_no_v }}
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.0'
      - name: test
        run: |
          make test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          target: base
          file: Dockerfile.multiarch
          tags: |
            ghcr.io/dhpollack/drone-docker-buildx:${{ steps.version.outputs.release }}
            ghcr.io/dhpollack/drone-docker-buildx:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
            ghcr.io/dhpollack/drone-docker-buildx:${{ steps.version.outputs.major }}
            ghcr.io/dhpollack/drone-docker-buildx:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            DOCKER_VERSION=${{ steps.version.outputs.release }}
  build-plugins:
    strategy:
      matrix:
        targetbin: [acr, gcr, ecr, heroku]
    runs-on: ubuntu-latest
    steps:
      - id: no_v
        run: |
          echo "ref_name_no_v=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
      - id: version
        uses: madhead/semver-utils@latest
        with:
          version: ${{ steps.no_v.outputs.ref_name_no_v }}
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.0'
      - name: test
        run: |
          make test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          target: xcr
          file: Dockerfile.multiarch
          tags: |
            ghcr.io/dhpollack/drone-docker-buildx-${{ matrix.targetbin }}:${{ steps.version.outputs.release }}
            ghcr.io/dhpollack/drone-docker-buildx-${{ matrix.targetbin }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
            ghcr.io/dhpollack/drone-docker-buildx-${{ matrix.targetbin }}:${{ steps.version.outputs.major }}
            ghcr.io/dhpollack/drone-docker-buildx-${{ matrix.targetbin }}:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            TARGETBIN=${{ matrix.targetbin }}
            DOCKER_VERSION=${{ steps.version.outputs.release }}
